{% set name = "keygen-py" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keygen_py-{{ version }}.tar.gz
  sha256: d3be5d6ab2590ad94a9f5ca5db40c1079f6a7d2d8e2c8c389b36b7cb768eb130

build:
  number: 1
  skip: true  # [py<39 and py>312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - make
    - perl
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - setuptools
    - wheel
    - maturin
  run:
    - python

test:
  imports:
    - keygen_sh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/terra-quantum-public/keygen-py
  summary: Unofficial Keygen SDK for Python. Integrate license activation and offline licensing. Wrapper around keygen-rs rust crate
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - sbtq
    - cedrictq
